### ISSUE TITLE
the shape of the predicted instance feature

### ISSUE THREAD

**Issue by wendyhuang2021** [Lans1ng/PointSAM#2]
Hi, I’m interested in your great work and have a question.

In the Methodology section, part C "Memory Bank Updating," you mention: “Given the predicted instance feature f^p_k​ with a positive prompt from the teacher’s image encoder.”

Is the shape of the predicted instance feature f^p_k the same as f^t_k and extracted from the location of a point prompt? Or is it calculated from the features in the instance mask?

**Comment by Lans1ng** [comment]
Thanks for your attention. The instance feature of the teacher encoder is also extracted from the location of a point prompt. Of course, extracting features using the predicted mask and taking the average is also worth trying.

**Comment by wendyhuang2021** [comment]
Thanks for your reply!
